pipeline:
  name: ERP_Configuration
  identifier: ERP_Configuration
  orgIdentifier: default
  projectIdentifier: ERP_System   # check actual project identifier in URL
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          codebase:
            connectorRef: ERP_Connector
            repoName: HiteshConsultancyService/erp-system-config
            build:
              type: branch
              spec:
                branch: main
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}       # ✅ required even if empty
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    shell: Bash
                    command: |
                      mvn clean install -DskipTests
        failureStrategies:         # ✅ required
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure

