pipeline:
  name: ERP_Configuration
  identifier: ERP_Configuration
  orgIdentifier: default
  projectIdentifier: ERP_System   # check identifier in URL (must be lowercase)
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ERP_Connector
        repoName: HiteshConsultancyService/erp-system-config
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    shell: Bash
                    command: |
                      mvn clean install -DskipTests
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure

